### ISSUE TITLE
microphone config files (audio + speech)

### ISSUE THREAD

**Issue by scaredycode** [UHHRobotics22-23/marimbabot#175] opened 2023-07-06 10:42 UTC
to assign devices (e.g. mic1 for audio feedback, mic2 for command detection)
as has been done in the vision node (config/cv_camera,yaml)

**Comment by yunlong-wang-cn** [comment] 2023-07-20 11:43
the problem is resolved in this PR #200, therefore close the issue

**Closed by yunlong-wang-cn** 2023-07-20 11:43 UTC
Labels: audio
